modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="gravity_qa"
version="1.0"
displayName="Gravity Jade Isolated Test Driver"
[[dependencies.gravity_qa]]
modId="sound_isolating_eraser"
mandatory=true
versionRange="[0.2.0,)"
ordering="AFTER"
side="BOTH"
