modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="neon_qa"
version="1.0"
displayName="Neon Tumor QA"
[[dependencies.neon_qa]]
modId="sound_isolating_eraser"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
